modify port names due to errors
ERROR: Error: Service "sync-gateway-service" is invalid: [spec.ports[0].name: invalid value 'APIPort': must have at most 63 characters and match regex [a-z0-9]([-a-z0-9]*[a-z0-9])?, spec.ports[1].name: invalid value 'AdminAPIPort': must have at most 63 characters and match regex [a-z0-9]([-a-z0-9]*[a-z0-9])?]